# Generated by Django 3.0.7 on 2021-03-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_slug', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
            ],
        ),
    ]
