# Generated by Django 3.0.7 on 2021-03-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="title_slug",
        ),
    ]
